version: "3.7"
volumes:  
    redis-volume: {}
    mongo-volume: {}

services:
    mongo:
        image: mongo:4
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo-volume:/data
    redis:
        image: redis:6
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-volume:/data
        healthcheck:
            test: "redis-cli -h 127.0.0.1 ping"            
            interval: 3s
            timeout: 1s
            retries: 5
