name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Load poetry cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Test with pytest
        run: |
          coverage run -m pytest -m "not kiwoom"
          coverage report
      - name: Codecov
        uses: codecov/codecov-action@v1.4.1
